# **Лабораторна робота №1 Вступ до машинного навчання.Елементи лінійної алгебри**
Варіант 1\
Галатенко Дарія Іванівна 3-16
# Завдання 1.
1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та
виведіть його значення.

In [ ]:
import numpy as np

# Створення вектора з першими 10-ма натуральними числами
vector = np.arange(1, 11)

# Виведення значення вектора
print("Одновимірний масив (вектор):", vector)

Одновимірний масив (вектор): [ 1  2  3  4  5  6  7  8  9 10]


# Завдання 2
1. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та
виведіть його значення.

In [ ]:
# Створення матриці 4x4, заповненої одиницями
matr = np.ones((4, 4), dtype=int)

# Виведення матриці
for row in matr:
    print(row)

[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]


# Завдання 3
1. Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні
від 1 до 5 та виведіть його значення.

In [ ]:
# Створення матриці 4x4 із випадковими числами від 1 до 5
matr = np.random.randint(1, 6, (4, 4))

# Виведення матриці
for row in matr:
    print(row)

[3 3 2 3]
[5 2 3 1]
[2 1 4 5]
[5 1 3 4]


# Завдання 4
1. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
# Створення масиву 3x3 з випадковими дійсними числами від 0 до 1
matr = np.random.random((3, 3))

# Виведення масиву
for row in matr:
    print(row)

[0.9258091  0.73873135 0.25911519]
[0.02131954 0.77225392 0.12615863]
[0.5847696  0.56880808 0.563596  ]


# Завдання 5
1. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими
числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
# Створення двох масивів розміром 6, заповнених випадковими цілими числами від 1 до 20
array1 = np.random.randint(1, 21, 6)
array2 = np.random.randint(1, 21, 6)

# Виконання поелементних операцій
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виведення результатів
print("Масив 1:", array1)
print("Масив 2:", array2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)

Масив 1: [ 9 14 17 10 15 20]
Масив 2: [ 9 13  4  4  9  7]
Додавання: [18 27 21 14 24 27]
Віднімання: [ 0  1 13  6  6 13]
Множення: [ 81 182  68  40 135 140]


# Завдання 6
1. Створіть два матриці 2x2, заповніть їх довільними цілими числами та знайдіть їх
добуток.

In [ ]:
# Створення двох матриць 2x2 з випадковими цілими числами від 1 до 11
matr1 = np.random.randint(1, 11, (2, 2))
matr2 = np.random.randint(1, 11, (2, 2))

# Обчислення добутку матриць
product = np.dot(matr1, matr2)

# Виведення матриць та їхнього добутку
print("Матриця 1:")
print(matr1)
print("\nМатриця 2:")
print(matr2)
print("\nДобуток матриць:")
print(product)

Матриця 1:
[[1 7]
 [5 8]]

Матриця 2:
[[10  3]
 [ 5 10]]

Добуток матриць:
[[45 73]
 [90 95]]


# Завдання 7
1. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
# Створення двох матриць 3x2 та 2x4 з випадковими цілими числами від 1 до 10
matr1 = np.random.randint(1, 11, size=(3, 2))
matr2 = np.random.randint(1, 11, size=(2, 4))

# Виведення матриць
print("Матриця 1 (3x2):")
print(matr1)

print("\nМатриця 2 (2x4):")
print(matr2)

# Знаходження добутку матриць
product = np.dot(matr1, matr2)

# Виведення результату
print("\nДобуток матриць:")
print(product)

Матриця 1 (3x2):
[[3 9]
 [5 9]
 [3 5]]

Матриця 2 (2x4):
[[ 7  1  4  2]
 [ 1  6 10  8]]

Добуток матриць:
[[ 30  57 102  78]
 [ 44  59 110  82]
 [ 26  33  62  46]]


# Завдання 8
1. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 7 та знайдіть її обернену матрицю.

In [ ]:
# Створення матриці 2x2 з випадковими цілими числами в діапазоні від 1 до 7
matr = np.random.randint(1, 8, size=(2, 2))

# Виведення початкової матриці
print("Матриця 2x2:")
print(matr)

# Перевірка, чи є матриця невиродженою (її визначник не нульовий)
det = np.linalg.det(matr)
if det != 0:
    # Обчислення оберненої матриці
    inverse_matr = np.linalg.inv(matr)
    print("\nОбернена матриця:")
    print(inverse_matr)
else:
    print("\nМатриця не має оберненої, оскільки її визначник дорівнює нулю.")

Матриця 2x2:
[[7 1]
 [6 2]]

Обернена матриця:
[[ 0.25  -0.125]
 [-0.75   0.875]]


# Завдання 9
1. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
# Створення матриці 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
matr = np.random.rand(3, 3)

# Виведення початкової матриці
print("Матриця 3x3:")
rounded_matr = np.round(matr, 2)  # Округлення матриці
print(rounded_matr)

# Транспонування матриці
transposed_matr = rounded_matr.T

# Виведення транспонованої матриці
print("\nТранспонована матриця:")
print(transposed_matr)

Матриця 3x3:
[[0.07 0.32 0.17]
 [0.3  0.12 0.28]
 [0.15 0.15 0.76]]

Транспонована матриця:
[[0.07 0.3  0.15]
 [0.32 0.12 0.15]
 [0.17 0.28 0.76]]


# Завдання 10
1. Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.

In [ ]:
# Створення матриці 3x4 з випадковими цілими числами в діапазоні від 1 до 10
matr = np.random.randint(1, 11, size=(3, 4))

# Створення вектора 4x1 з випадковими цілими числами в діапазоні від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))

# Виведення матриці та вектора
print("Матриця 3x4:")
print(matr)

print("\nВектор 4x1:")
print(vector)

# Знаходження добутку матриці та вектора
product = np.dot(matr, vector)

# Виведення результату
print("\nДобуток матриці та вектора:")
print(product)

Матриця 3x4:
[[ 7  7  8 10]
 [ 7  2  2  9]
 [ 2  9  4  6]]

Вектор 4x1:
[[5]
 [9]
 [6]
 [7]]

Добуток матриці та вектора:
[[216]
 [128]
 [157]]


# Завдання 11
1. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [ ]:
# Створення матриці 2x3 з випадковими цілими числами від 1 до 10
matr = np.random.randint(1, 11, size=(2, 3))

# Створення вектора 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Виведення матриці та вектора
print("Матриця 2x3:")
print(matr)

print("\nВектор 3x1:")
print(vector)

# Знаходження добутку матриці та вектора
product = np.dot(matr, vector)

# Виведення результату
print("\nДобуток матриці та вектора:")
print(product)

Матриця 2x3:
[[5 8 4]
 [3 7 3]]

Вектор 3x1:
[[ 4]
 [ 3]
 [10]]

Добуток матриці та вектора:
[[84]
 [63]]


# Завдання 12
1. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню суму.

In [ ]:
# Створення двох матриць 2x2 з випадковими цілими числами від 1 до 10
matr1 = np.random.randint(1, 11, size=(2, 2))
matr2 = np.random.randint(1, 11, size=(2, 2))

# Виведення початкових матриць
print("Перша матриця 2x2:")
print(matr1)

print("\nДруга матриця 2x2:")
print(matr2)

# Обчислення суми матриць
sum_matr = matr1 + matr2

# Виведення результату
print("\nСума двох матриць:")
print(sum_matr)

Перша матриця 2x2:
[[5 5]
 [2 4]]

Друга матриця 2x2:
[[ 4  8]
 [10  7]]

Сума двох матриць:
[[ 9 13]
 [12 11]]


# Завдання 13
1. Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть їх добуток.

In [ ]:
# Створення двох матриць 2x2 з випадковими дійсними числами від 0 до 1
matr1 = np.random.rand(2, 2)
matr2 = np.random.rand(2, 2)

# Виведення початкових матриць (округлені до 2 знаків для зручності)
print("Перша матриця 2x2:")
print(np.round(matr1, 2))

print("\nДруга матриця 2x2:")
print(np.round(matr2, 2))

# Обчислення добутку матриць
product_matr = np.dot(matr1, matr2)

# Виведення результату (також округлено)
print("\nДобуток двох матриць:")
print(np.round(product_matr, 2))

Перша матриця 2x2:
[[0.96 0.97]
 [0.98 0.78]]

Друга матриця 2x2:
[[0.86 0.26]
 [0.91 0.47]]

Добуток двох матриць:
[[1.7  0.7 ]
 [1.55 0.62]]


# Завдання 14
1. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть суму елементів матриці.

In [ ]:
# Створення матриці 5x5 з випадковими дійсними числами від 0 до 1
matr = np.random.rand(5, 5)

# Виведення матриці (округленої до 2 знаків для зручності)
print("Матриця 5x5:")
print(np.round(matr, 2))

# Знаходження суми всіх елементів матриці
sum_elements = np.sum(matr)

# Виведення суми елементів матриці
print("\nСума всіх елементів матриці:", round(sum_elements, 2))

Матриця 5x5:
[[0.76 0.37 0.25 0.83 0.28]
 [0.62 0.79 0.64 0.29 0.31]
 [0.99 0.27 0.44 0.93 0.65]
 [0.23 0.16 0.   0.   0.67]
 [0.21 0.18 0.59 0.83 0.62]]

Сума всіх елементів матриці: 11.94


# Завдання 15
1. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


In [ ]:
# Створення матриці 3x3 з випадковими дійсними числами від -1 до 1
matr = np.random.uniform(-1, 1, (3, 3))

# Виведення матриці (округленої до 2 знаків для зручності)
print("Матриця 3x3:")
print(np.round(matr, 2))

# Знаходження суми елементів кожного рядка та перетворення у вектор-стовпець
sum_vector = np.sum(matr, axis=1).reshape(3, 1)

# Виведення вектора-стовпця (округленого)
print("\nВектор-стовпчик (сума елементів кожного рядка):")
print(np.round(sum_vector, 2))

Матриця 3x3:
[[-0.18  0.35 -0.98]
 [ 0.93 -0.72 -0.44]
 [ 0.47 -0.87 -0.43]]

Вектор-стовпчик (сума елементів кожного рядка):
[[-0.81]
 [-0.23]
 [-0.84]]


# Висновок
Під час виконання цієї лабораторної роботи я набула практичних навичок створення та обробки масивів і матриць у Python за допомогою бібліотеки NumPy. Використання цієї бібліотеки значно спростило програмування та дозволило ефективно працювати з масивами та матрицями. Здобуті знання та навички є важливими для подальшого вивчення програмування та аналізу даних.